services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-hojadevida
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.hojadevida.digital`) && PathPrefix(`/`)"
      - "traefik.http.routers.app.middlewares=app-stripprefix"
      - "traefik.http.middlewares.app-stripprefix.stripprefix.prefixes=/"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=resolver"
      - "traefik.http.middlewares.app.addprefix.prefix=/"
      - traefik.http.routers.frontend.middlewares=www
      - traefik.http.middlewares.www.redirectregex.regex=^https://www.app.hojadevida.digital/(.*)
      - traefik.http.middlewares.www.redirectregex.replacement=https://app.hojadevida.digital/(.*)$$1
      - traefik.http.middlewares.www.redirectregex.permanent=true

networks:
  default:
      name: carnet
      external: true