server {
    listen 80;
    server_name app.hojadevida.digital;

    root /usr/share/nginx/html/.output/public;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }
}